<?php
/**
 * Created by PhpStorm.
 * User: king
 * Date: 17-4-21
 * Time: 上午10:49
 */

namespace backend\modules\settle_manage\models;

use common\models\BaseRecord;

use yii\db\Expression;
class OrderFinanceMap extends BaseRecord
{


    public static function tableName()
    {
        return parent::OrderFinanceRecord;
    }

    public function formDataPreHandler(&$formData, $record = null)
    {
        parent::formDataPreHandler($formData, $record); // TODO: Change the autogenerated stub
    }

    public function myOrderSettleInsert($formData)
    {
        return $this->insertRecord($formData);
    }

}